name: hosts

on:
  schedule:
    - cron: '0/30 * * * *'

  workflow_dispatch:
    inputs:
      dns:
        description: 'DNS'
        required: true
        default: 'Aliyun'
        type: choice
        options:
        - 'Google'
        - 'OpenDNS'
        - 'AT&T'
        - 'Aliyun'
        - 'LG'
        - 'IONICA'

jobs:
  hosts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Init Env
        run : |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          sudo timedatectl set-timezone "Asia/Shanghai"
          python -m pip install --upgrade pip setuptools
          python -m pip install urllib3
          
      - name: Get Github Hosts
        shell: python
        run: |
          import os, time, json, urllib3

          class dnsChecker():
              def __init__(self) -> None:
                  self.dnsServers = {
                      "Google": {
                          "idx": "4",
                          "provider": " Google",
                          "location": "Mountain View CA, United States",
                          "country": "us"
                      },
                      "OpenDNS": {
                          "idx": "1",
                          "provider": " OpenDNS",
                          "location": "Holtsville NY, United States",
                          "country": "us"
                      },
                      "AT&T": {
                          "idx": "72",
                          "provider": "AT&T Services",
                          "location": "Miami, United States",
                          "country": "us"
                      },
                      "Aliyun": {
                          "idx": "364",
                          "provider": "Aliyun Computing Co. Ltd",
                          "location": "Hangzhou, China",
                          "country": "cn"
                      },
                      "LG": {
                          "idx": "336",
                          "provider": "LG Dacom Corporation",
                          "location": "Seoul, South Korea",
                          "country": "kr"
                      },
                      "IONICA": {
                          "idx": "13",
                          "provider": "IONICA LLC",
                          "location": "Ramenskoye, Russia",
                          "country": "ru"
                      }
                  }
                  self.dnsidx = self.dnsServers['Aliyun']['idx']
                  self.headers = {
                      'accept': 'application/json, text/javascript, */*; q=0.01',
                      'content-type': 'application/x-www-form-urlencoded; charset=UTF-8', 
                      'x-requested-with': 'XMLHttpRequest',
                      'origin': 'https://dnschecker.org',
                      'referer': 'https://dnschecker.org/',
                      'x-requested-with': 'XMLHttpRequest', 
                  }
                  self.PM = urllib3.PoolManager()

                  url = 'https://dnschecker.org/ajax_files/gen_csrf.php'
                  res = self.PM.request('POST', url, headers=self.headers)
                  if res.status == 200:
                      data = None
                      data = json.loads(res.data.decode('utf-8'))
                      if data != None and 'csrf' in data:
                          self.headers['csrftoken'] = data['csrf']

              def setServers(self, servers=''):
                  if servers in self.dnsServers:
                      self.dnsidx = self.dnsServers[servers]['idx']

              def getServers(self, servers=''):
                  if servers == '': 
                      for i in self.dnsServers:
                          if self.dnsServers[i]['idx'] == self.dnsidx:
                              servers = i
                  if servers in self.dnsServers:
                      return self.dnsServers[servers]
                  else:
                      return None
                      

              def check(self, qname='', rdtype='A', servers=''):
                  if servers == '': 
                      servers = self.dnsidx
                  ret = False
                  ips = []
                  try:
                      url = 'https://dnschecker.org/ajax_files/api/{}/{}/{}?upd=500.000'.format(servers, rdtype, qname)
                      res = self.PM.request('POST', url, headers=self.headers)

                      if res.status == 200:
                          data = None
                          data = json.loads(res.data.decode('utf-8'))
                          if data != None and 'result' in data and 'ips' in data['result']:
                              ret = True
                              ips = data['result']['ips'].split('<br />')
                          else:
                              print(res.data.decode('utf-8'))
                      else:
                          print(res.data.decode('utf-8'))
                  except Exception as err:
                      print(err)
                  return ret, ips


          if __name__ == '__main__':
              gitHubDoMains = [
                  "github.io",
                  "github.com",
                  "github.blog",
                  "github.community",
                  "api.github.com",
                  "gist.github.com",
                  "codeload.github.com",
                  "central.github.com",
                  "collector.github.com",
                  "raw.github.com",
                  "docs.github.com",
                  "assets-cdn.github.com",
                  "raw.githubusercontent.com",
                  "camo.githubusercontent.com",
                  "cloud.githubusercontent.com",
                  "media.githubusercontent.com",
                  "desktop.githubusercontent.com",
                  "objects.githubusercontent.com",
                  "favicons.githubusercontent.com",
                  "avatars5.githubusercontent.com",
                  "avatars4.githubusercontent.com",
                  "avatars3.githubusercontent.com",
                  "avatars2.githubusercontent.com",
                  "avatars1.githubusercontent.com",
                  "avatars0.githubusercontent.com",
                  "avatars.githubusercontent.com",
                  "user-images.githubusercontent.com",
                  "copilot-proxy.githubusercontent.com",
                  "github-releases.githubusercontent.com",
                  "pipelines.actions.githubusercontent.com",
                  "pipelinesghubeus7.actions.githubusercontent.com",
                  "githubstatus.com",
                  "collector.githubapp.com",
                  "github.githubassets.com",
                  "analytics.githubassets.com",
                  "github.map.fastly.net",
                  "github.global.ssl.fastly.net",
                  "github-cloud.s3.amazonaws.com",
                  "github-com.s3.amazonaws.com",
                  "github-production-release-asset-2e65be.s3.amazonaws.com",
                  "github-production-user-asset-6210df.s3.amazonaws.com",
                  "github-production-repository-file-5c1aeb.s3.amazonaws.com"
              ]
              
              dockerDoMains = [
                  "registry.hub.docker.com",
                  "hub.docker.com",
                  "ghcr.io",
                  "gcr.io",
                  "k8s.gcr.io",
                  "quay.io"
              ]
              
              tMMDoMains = [
                  "themoviedb.org",
                  "www.themoviedb.org",
                  "api.themoviedb.org",
                  "tmdb.org",
                  "api.tmdb.org",
                  "image.tmdb.org",
                  "opensubtitles.org",
                  "www.opensubtitles.org",
                  "api.opensubtitles.org",
                  "assets.fanart.tv"
              ]
              
              dnsobj = dnsChecker()

              dnsservers = 'Aliyun'
              if '${{ inputs.dns }}' != '':
                  dnsservers = '${{ inputs.dns }}'
              dnsobj.setServers(dnsservers)

              dnsList = []
              dnsList.append('# ING Hosts Start')
              dnsList.append('# Raw Url: https://raw.githubusercontent.com/skywrt/hosts/main/hosts')
              dnsList.append('# CDN Url: https://gcore.jsdelivr.net/gh/skywrt/hosts@main/hosts')
              dnsList.append('# CDN Url: https://cdn.staticaly.com/gh/skywrt/hosts/main/hosts')
              dnsList.append('# DNS Servers: {}'.format(dnsobj.getServers()['provider']))
              dnsList.append('# Update at: {}'.format(time.strftime("%Y-%m-%d %H:%M:%S")))

              # GitHub
              dnsList.append('# GitHub Hosts Start')
              for domain in gitHubDoMains:
                  ret, ips = dnsobj.check(domain, 'A')
                  if ret == True:
                      for ip in ips:
                          dnsList.append((ip.ljust(16) + domain))
                          break  # 只取第一个吧
              dnsList.append('# GitHub Hosts End')
              
              # Docker
              dnsList.append('# Docker Hosts Start')
              for domain in dockerDoMains:
                  ret, ips = dnsobj.check(domain, 'A')
                  if ret == True:
                      for ip in ips:
                          dnsList.append((ip.ljust(16) + domain))
                          break  # 只取第一个吧
              dnsList.append('# Docker Hosts End')
              
              # TMM
              dnsList.append('# TMM Hosts Start')
              for domain in tMMDoMains:
                  ret, ips = dnsobj.check(domain, 'A')
                  if ret == True:
                      for ip in ips:
                          dnsList.append((ip.ljust(16) + domain))
                          break  # 只取第一个吧
              dnsList.append('# TMM Hosts End')
              
              dnsList.append('# ING Hosts End')
              
              with open('hosts', 'w', encoding="utf-8") as f:
                  f.writelines('\n'.join(dnsList))

      - name: Check and Push
        run: |
          if [ -n "$(git status -s | grep hosts)" ]; then
            git add hosts
            git commit -m "update $(date +%Y-%m-%d" "%H:%M:%S)"
            git push -f
          fi

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0.1
          keep_minimum_runs: 0
